// ghost init
// Refactor Zustand store for memory,
// Tweak LLM prompt for coaching,
// Tune breathing break animation flow,
// Fix session feedback logging bug,
// Fix webcam permission edge case,
// Fix session feedback logging bug,
// Style profile page layout,
// Style profile page layout,
// Refactor Zustand store for memory,
// Add new mini-puzzle to break set
// Add placeholder for MYA memory component,
// Fix session feedback logging bug,
// Tune breathing break animation flow,
// Fix session feedback logging bug,
// Fix webcam permission edge case,
// Fix session feedback logging bug,
// Style profile page layout,
// Fix session feedback logging bug,
// Refactor Zustand store for memory,
// Style profile page layout,
